### PR TITLE
build mac os installations for 1.8.0

### PR DESCRIPTION
**Pull request by KKopyscinski**

### CODE REVIEW

**Comment by utzig** [comment]
Shouldn't it have `newtmgr` as well?

**Comment by KKopyscinski** [comment]
Ah yes. I was following "howto" and simply forgot about it. Will add it shortly

**Comment by KKopyscinski** [comment]
@rymanluk Could you review this?

**Comment by rymanluk** [comment]
@KKopyscinski  maybe somebody with Mac OS?

**Review by utzig — APPROVED** [review]
I don't have a mac anymore, but since nobody verified, I will just merge this and if it doesn't work someone else can send a PR fixing!

**Pull request merged**
